import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getData } from "@/utils/getData";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories: any = await getData(
    "https://api.escuelajs.co/api/v1/categories"
  );

  return (
    <html lang="en">
      <Header categories={categories} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
